### ISSUE TITLE
I can't get "Model thingy" to display anything

### ISSUE THREAD

**Issue by lannoene** [TheFearsomeDzeraora/LM2L#2]
Whenever I try to use it, all of the windows are completely white. Maybe there is some trivial thing that I'm doing wrong? I don't know.

**Comment by hadashisora** [comment]
Sorry for the late reply. I never completed that part of it, so it's supposed to be like that actually. This project isn't developed anymore, if you want something that can view LM2 stuff, check out [Switch Toolbox](https://github.com/KillzXGaming/Switch-Toolbox).
